### ISSUE TITLE
----------

### ISSUE THREAD

**Issue by ghost** [ET-Lang/STD#11]
-

**Comment by pglapds** [comment]
## Example & Use

<br>
<br>

**Example 1** , **1.** Evolution,  **Concept** 

![Ampersand_Evolution2](https://user-images.githubusercontent.com/46846354/58900400-7c1de200-86d5-11e9-938f-1cbd52ab2142.png)

Evolution: Alpha **->** Beta **->**  Dev **->** Stable **->** Release. 

<br>
<br>

**//** Or versions: Build, Rebuild, Revision.... 

<br>
<br>

**Example 2** , **2.** Evolution,  **Use, Shell** 

1. > 1. & , normal use
2. > 2. :&:  , see errors 
3. > 3. :& , acess settings
4. > 4. &: , acess url 
5. > 5. -&- , acess settings design
6. > 6.  _&_ , acess protocol
7. > 7. et , acess & run file
9. > 9.  _et_  , acess & run file in cloud
10. > 10.  -et-  , docs & examples
11. > 11.  :et , repl 
12. > 12.  :et: , save 
13. > 13.  et: , transfer 
14. > 14.  .et: , user and password
15. > 15.  .et . , class, methods, special use
16. > 16.  :et . , libs
17. > 17.  et: . , process 
18. > 18.  .&:  , sys
19. > 19.  .& . , io 
20. > 20.  :& . , folder
21. > 21.  &: . , user, hostname, host, localhost, ip... 


<br>
<br>

**Comment by pglapds** [comment]
& reply , reference: https://github.com/ET-Lang/STD/issues/4

### **Objective:** Use the & symbol as default for the shell and as the default symbol for the project with the name et.

**Reason:** The **&** symbol would represent the initial, final version.  Read in: https://en.wiktionary.org/wiki/%26

What does ampersand symbolize?

The ampersand is a visual representation of the phrase “and, per se and.” It is a graphic representation of the Latin “et,” which translates to “and.” That definition is how the ampersand is most commonly used today — as an inclusionary symbol meaning “and.”

#    

**I. About this symbol, About this symbol in History and Use**

1. ***def*** Symbol &, Etymology
A stylized form of Latin et (“and”). Romans used such symbols (ligatures) from at least the first century CE, but the character may not have acquired its present form until the advent of calligraphy in the Middle Ages. Compare ⁊, of same meaning and similar derivation.

**II. Use**
1. ***def*** Symbol &, Conjunction ```Siglum of "and"```
    1. ***def*** Symbol &,
    2. (programming) Used in some programming languages for different purposes.
    3. De referencing memory address.
    4. Bitwise "and" operator.
    5. (networking) In a URL, separates each field-value pair of a query string .

**III. More, Synonyms  ⁊**
1. ***def*** Symbol &, Synonyms  ⁊ 
    1. Derived terms
    2. (mathematics) ⅋
    3. & ;
    4. v& (to be arrested)

<br>


https://github.com/ET-Lang/ET/wiki/Compiler-CLI

**Comment by pglapds** [comment]
## Example & Use

<br>
<br>

**Example 1** , **1.** Evolution,  **Concept** 

![Ampersand_Evolution2](https://user-images.githubusercontent.com/46846354/58900400-7c1de200-86d5-11e9-938f-1cbd52ab2142.png)

Evolution: Alpha **->** Beta **->**  Dev **->** Stable **->** Release. 

<br>
<br>

**//** Or versions: Build, Rebuild, Revision.... 

<br>
<br>

**Example 2** , **2.** Evolution,  **Use, Shell** 

1. > 1. & , normal use
2. > 2. :&:  , see errors 
3. > 3. :& , acess settings
4. > 4. &: , acess url 
5. > 5. -&- , acess settings design
6. > 6.  _&_ , acess protocol
7. > 7. et , acess & run file
9. > 9.  _et_  , acess & run file in cloud
10. > 10.  -et-  , docs & examples
11. > 11.  :et , repl 
12. > 12.  :et: , save 
13. > 13.  et: , transfer 
14. > 14.  .et: , user and password
15. > 15.  .et . , class, methods, special use
16. > 16.  :et . , libs
17. > 17.  et: . , process 
18. > 18.  .&:  , sys
19. > 19.  .& . , io 
20. > 20.  :& . , folder
21. > 21.  &: . , user, hostname, host, localhost, ip... 


<br>
<br>
