### ISSUE TITLE
--

### ISSUE THREAD

**Issue by ghost** [ET-Lang/STD#2]
-

**Comment by BaseMax** [comment]
> 
> 
> Add unit tests to REPL: https://repl.it/@et

Hey,

Can you explain what you means?
https://repl.it/@BaseMax

Regards,
Max

**Comment by pglapds** [comment]
> > Add unit tests to REPL: https://repl.it/@et
> 
> Hey,
> 
> Can you explain what you means?
> https://repl.it/@BaseMax
> 
> Regards,
> Max

Example-test file  "https://repl.it/@et/array"

Example-test file  "https://repl.it/@et/style"

Example-test file  "https://repl.it/@et/cgi"

Example-test file  "https://repl.it/@et/io"

...
